begin;
create function pg_temp.id(n int) returns uuid language sql immutable as $$select ('48480000-0000-4000-8000-'||lpad(n::text,12,'0'))::uuid$$;
create function pg_temp.ok(v boolean,m text) returns void language plpgsql as $$begin if v is distinct from true then raise exception 'ASSERTION: %',m; end if; end$$;
create function pg_temp.reject(q text,code text) returns void language plpgsql as $$begin begin execute q; exception when others then if sqlstate=code then return; end if; raise; end; raise exception 'Unexpected success'; end$$;
insert into auth.users(id,email) values(pg_temp.id(1),'worker-assessment@test.invalid');
insert into public.users(id,email) values(pg_temp.id(1),'worker-assessment@test.invalid');
insert into public.tenants(id,slug,name) values(pg_temp.id(11),'worker-assessment','Worker fixture');
insert into public.tenant_users(tenant_id,user_id,role) values(pg_temp.id(11),pg_temp.id(1),'owner');
insert into public.control_libraries(version,published_at,published_by,change_log,control_count)
 values('worker-assessment-v1',now(),'test','Synthetic fixture',2);
insert into public.controls(id,library_version,title,obligation,domain,severity,citations,evidence_required,assessment_questions,scoring,remediation_patterns,introduced_in_version)
 select 'WA-'||n,'worker-assessment-v1','Fixture','Fixture','SEC','low','[]','[]','[]','{"baseline":0,"weight":1,"penaltyPoints":10,"maxPenaltyINR":1000000}','{}','worker-assessment-v1' from generate_series(1,2) n;
insert into public.estates(id,tenant_id,name,slug) values(pg_temp.id(22),pg_temp.id(11),'Synthetic estate','synthetic');
insert into public.engagements(id,tenant_id,estate_id,library_version,title) values(pg_temp.id(21),pg_temp.id(11),pg_temp.id(22),'worker-assessment-v1','New assessment');
insert into public.workload_identities(id,tenant_id,agent_name,spiffe_id,status)
 values(pg_temp.id(31),pg_temp.id(11),'parikshan','spiffe://axiom.test/parikshan','active');
create temporary table issued as select (public.delegate_workload_task(pg_temp.id(11),pg_temp.id(1),pg_temp.id(31),'parikshan',pg_temp.id(22),pg_temp.id(21),pg_temp.id(41),repeat('a',64),repeat('b',64),array['control_library.read','findings.write'],clock_timestamp()+interval '10 minutes')->>'run_id')::uuid run_id;
grant select on issued to service_role;
create function pg_temp.start_tool(proof text default repeat('b',64),input_hash text default repeat('a',64),deadline timestamptz default clock_timestamp()+interval '5 minutes') returns jsonb language sql as $$
 select public.start_workload_assessment(pg_temp.id(11),(select run_id from issued),pg_temp.id(31),proof,input_hash,deadline)$$;
create function pg_temp.result() returns jsonb language sql immutable as $$select '{"library_version":"worker-assessment-v1","posture_score":50,"estimated_exposure_inr":10000000,"findings":[{"control_id":"WA-1","score":0,"risk_points":10,"rationale":"No answers comply"},{"control_id":"WA-2","score":100,"risk_points":0,"rationale":"All answers comply"}]}'::jsonb$$;
create function pg_temp.finish_tool(result jsonb default pg_temp.result(),deadline timestamptz default clock_timestamp()+interval '5 minutes') returns jsonb language sql as $$
 select public.complete_workload_assessment(pg_temp.id(11),(select run_id from issued),pg_temp.id(31),repeat('b',64),(select library_digest from public.workload_assessment_packets where run_id=(select run_id from issued)),result,deadline)$$;
select pg_temp.start_tool();
select pg_temp.finish_tool();
create function pg_temp.confirm_tool() returns jsonb language sql as $$select public.confirm_workload_assessment(pg_temp.id(11),(select run_id from issued))$$;
set local role service_role;
select pg_temp.ok(public.confirm_workload_assessment(pg_temp.id(91),(select run_id from issued))->>'error'='confirmation_unavailable','foreign tenant refuses');
select pg_temp.ok(public.confirm_workload_assessment(pg_temp.id(11),pg_temp.id(92))->>'error'='confirmation_unavailable','unknown run refuses');
reset role;
savepoint conflicting_receipt;
update public.workload_assessment_packets set started_receipt=completed_receipt;
set local role service_role;
select pg_temp.ok(pg_temp.confirm_tool()->>'error'='confirmation_conflict','unbound receipt refuses');
reset role;
rollback to conflicting_receipt;
savepoint conflicting_input;
update public.agent_runs set input_redacted_hash=repeat('c',64) where id=(select run_id from issued);
set local role service_role;
select pg_temp.ok(pg_temp.confirm_tool()->>'error'='confirmation_conflict','changed run input refuses');
reset role;
rollback to conflicting_input;
savepoint conflicting_result;
update public.workload_assessment_packets set result=jsonb_set(result,'{posture_score}','60');
set local role service_role;
select pg_temp.ok(pg_temp.confirm_tool()->>'error'='confirmation_conflict','result digest is independently checked');
reset role;
rollback to conflicting_result;
savepoint cancelled;
update public.agent_runs set status='cancelled',completed_at=clock_timestamp() where id=(select run_id from issued);
set local role service_role;
select pg_temp.ok(pg_temp.confirm_tool()->>'error'='terminal_conflict','concurrent terminal state preserved');
select pg_temp.ok((select status='cancelled' from public.agent_runs where id=(select run_id from issued)),'no cancellation overwrite');
reset role;
rollback to cancelled;
create function pg_temp.fail_confirmation() returns trigger language plpgsql as $$begin if new.action_type='workload.task_completed' then raise exception 'synthetic audit failure'; end if; return new; end$$;
create trigger fail_confirmation before insert on public.audit_ledger for each row execute function pg_temp.fail_confirmation();
set local role service_role;
select pg_temp.reject('select pg_temp.confirm_tool()','P0001');
select pg_temp.ok((select status='running' and completed_at is null from public.agent_runs where id=(select run_id from issued)),'audit fault leaves run unconfirmed');
select pg_temp.ok((select finalized_receipt is null from public.workload_assessment_packets),'audit fault rolls back finalization');
reset role;
drop trigger fail_confirmation on public.audit_ledger;
-- Reconciliation records the truth of a past authorized commit. It does not
-- revive authority after later demotion, halt, archival or task revocation.
update public.tenant_users set role='viewer' where tenant_id=pg_temp.id(11);
update public.estates set status='archived' where id=pg_temp.id(22);
update public.workload_task_delegations set revoked_at=clock_timestamp();
update public.kill_switch_state set engaged=true where scope_key='global';
set local role service_role;
select pg_temp.ok(pg_temp.confirm_tool()->>'status'='succeeded','confirms past committed result after authority ended');
select pg_temp.ok(pg_temp.confirm_tool()->>'status'='succeeded','reconciliation retry is idempotent');
select pg_temp.ok(pg_temp.finish_tool()->>'error'='task_refused','confirmation does not revive worker write authority');
select pg_temp.ok((select status='succeeded' and output_redacted_hash is not null and completed_at is not null and error is null and total_tokens=0 and cost_usd=0 from public.agent_runs where id=(select run_id from issued)),'confirmed deterministic run fields');
select pg_temp.ok((select count(*)=1 from public.audit_ledger where tenant_id=pg_temp.id(11) and action_type='workload.task_completed'),'one completion receipt');
select pg_temp.ok((select count(*)=2 from public.findings where tenant_id=pg_temp.id(11)),'confirmation never duplicates findings');
reset role;
set local role authenticated;
select pg_temp.reject('select pg_temp.confirm_tool()','42501');
reset role;
set local role anon;
select pg_temp.reject('select pg_temp.confirm_tool()','42501');
reset role;
rollback;
