begin;
create function pg_temp.id(n int) returns uuid language sql immutable as $$select ('74740000-0000-4000-8000-'||lpad(n::text,12,'0'))::uuid$$;
create function pg_temp.ok(v boolean,m text) returns void language plpgsql as $$begin if v is distinct from true then raise exception 'ASSERTION: %',m; end if; end$$;
create function pg_temp.reject(q text) returns void language plpgsql as $$begin begin execute q; exception when others then return; end; raise exception 'accepted forbidden statement'; end$$;
create function pg_temp.hash(v text) returns text language sql immutable security definer set search_path='' as $$select encode(pg_catalog.sha256(convert_to(v,'UTF8')),'hex')$$;
create function pg_temp.request(n int,tenant int default 1,prior int default null) returns text language sql as $$
 select jsonb_build_object('schemaVersion',1,'purpose','controller-backend-issue','credentialId',pg_temp.id(n),'tenantId',pg_temp.id(tenant),
 'configurationSha256',repeat('a',64),'approvalReference',pg_temp.id(90+n),'predecessorId',pg_temp.id(prior),
 'issuedAt',floor(extract(epoch from now())),'expiresAt',floor(extract(epoch from now()))+3600)::text
$$;
create function pg_temp.issue(v text) returns jsonb language sql as $$select controller_security.issue_credential(v,pg_temp.hash(v))$$;
insert into public.tenants(id,slug,name) values(pg_temp.id(1),'credential-review-a','Credential review A'),(pg_temp.id(2),'credential-review-b','Credential review B');
insert into controller_security.credentials(id,tenant_id,expires_at) values(pg_temp.id(80),pg_temp.id(1),clock_timestamp()+interval '1 hour');
select set_config('test.first',pg_temp.request(10),true);
select set_config('test.next',pg_temp.request(11,1,10),true);
select set_config('test.foreign',pg_temp.request(12,2),true);
set local role axiom_controller_issuer;
select pg_temp.reject($q$select pg_temp.issue(pg_temp.request(80))$q$);
select pg_temp.reject($q$select pg_temp.issue(pg_temp.request(81,1,80))$q$);
select pg_temp.ok(pg_temp.issue(current_setting('test.first'))->>'status'='active','issuer registers reviewed lease');
select pg_temp.ok(pg_temp.issue(current_setting('test.first'))=pg_temp.issue(current_setting('test.first')),'exact issue is idempotent');
select pg_temp.reject('select * from controller_security.credentials');
select pg_temp.reject('update controller_security.credentials set revoked_at=null');
select pg_temp.reject('select * from controller_security.issuances');
select pg_temp.reject('select * from public.users');
select pg_temp.reject('select public.reserve_assessment_schedules(''test'')');
select pg_temp.reject('select controller_security.checked_request(''{}'',''a'',''controller-backend-issue'')');
select pg_temp.ok(not exists(select 1 from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='controller_security' and has_function_privilege(current_user,p.oid,'EXECUTE') and p.proname not in ('issue_credential','revoke_credential','credential_status')),'only three private issuer functions');
select pg_temp.ok(not exists(select 1 from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.prosecdef and has_function_privilege(current_user,p.oid,'EXECUTE') and p.proname<>'has_tenant_role'),'issuer has no public mutation RPC');
select pg_temp.reject($q$select pg_temp.issue(jsonb_set(current_setting('test.first')::jsonb,'{tenantId}',to_jsonb(pg_temp.id(2)))::text)$q$);
select pg_temp.reject($q$select pg_temp.issue(jsonb_set(current_setting('test.first')::jsonb,'{approvalReference}',to_jsonb(pg_temp.id(88)))::text)$q$);
select pg_temp.reject($q$select controller_security.issue_credential(current_setting('test.first'),repeat('b',64))$q$);
select pg_temp.reject($q$select pg_temp.issue(replace(pg_temp.request(14),'"schemaVersion": 1','"schemaVersion": 1,"schemaVersion": 1'))$q$);
select pg_temp.reject($q$select pg_temp.issue(jsonb_set(pg_temp.request(14)::jsonb,'{issuedAt}','true')::text)$q$);
select pg_temp.reject($q$select pg_temp.issue(jsonb_set(pg_temp.request(14)::jsonb,'{issuedAt}',to_jsonb(floor(extract(epoch from now()))-301))::text)$q$);
select pg_temp.reject($q$select pg_temp.issue(jsonb_set(pg_temp.request(14)::jsonb,'{expiresAt}',to_jsonb(floor(extract(epoch from now()))+3601))::text)$q$);
select pg_temp.reject($q$select pg_temp.issue(jsonb_set(pg_temp.request(14)::jsonb,'{credentialId}','"00000000-0000-0000-0000-000000000000"')::text)$q$);
select pg_temp.reject($q$select pg_temp.issue(jsonb_set(pg_temp.request(14)::jsonb,'{unexpected}','1')::text)$q$);
select pg_temp.ok(pg_temp.issue(current_setting('test.foreign'))->>'status'='active','second tenant independent');
select pg_temp.reject($q$select pg_temp.issue(pg_temp.request(14,1,12))$q$);
select pg_temp.ok(pg_temp.issue(current_setting('test.next'))->>'status'='active','renewal creates fresh lease');
select pg_temp.reject($q$select pg_temp.issue(pg_temp.request(14,1,10))$q$);
reset role;
select pg_temp.ok((select count(*)=3 from controller_security.issuances where credential_id in(pg_temp.id(10),pg_temp.id(11),pg_temp.id(12))),'exact retries and refused branches create no extra leases');
select pg_temp.ok((select revoked_at is null from controller_security.credentials where id=pg_temp.id(10)),'renewal preserves predecessor until explicit retirement');
select pg_temp.reject($q$update controller_security.credentials set expires_at=expires_at+interval '1 second' where id=pg_temp.id(10)$q$);
select pg_temp.reject($q$update controller_security.credentials set tenant_id=pg_temp.id(2) where id=pg_temp.id(10)$q$);
select pg_temp.reject($q$delete from controller_security.credentials where id=pg_temp.id(10)$q$);
select pg_temp.reject($q$delete from controller_security.issuances where credential_id=pg_temp.id(10)$q$);
select set_config('test.revoke',jsonb_build_object('schemaVersion',1,'purpose','controller-backend-revoke','credentialId',pg_temp.id(10),'tenantId',pg_temp.id(1),
 'configurationSha256',repeat('a',64),'approvalReference',pg_temp.id(99),'issuanceSha256',pg_temp.hash(current_setting('test.first')))::text,true);
set local role axiom_controller_issuer;
select pg_temp.ok(controller_security.revoke_credential(current_setting('test.revoke'),pg_temp.hash(current_setting('test.revoke')))->>'status'='revoked','explicit retirement succeeds');
select pg_temp.ok(controller_security.revoke_credential(current_setting('test.revoke'),pg_temp.hash(current_setting('test.revoke')))->>'status'='revoked','same revocation idempotent');
select pg_temp.reject($q$select pg_temp.issue(current_setting('test.first'))$q$);
select pg_temp.reject($q$select pg_temp.issue(pg_temp.request(14,1,10))$q$);
select pg_temp.reject($q$select controller_security.credential_status(pg_temp.id(11),pg_temp.id(2),pg_temp.hash(current_setting('test.next')))$q$);
select pg_temp.ok(controller_security.credential_status(pg_temp.id(11),pg_temp.id(1),pg_temp.hash(current_setting('test.next')))->>'status'='active','successor independent of predecessor retirement');
reset role;
select pg_temp.reject($q$update controller_security.credentials set revoked_at=null where id=pg_temp.id(10)$q$);
select pg_temp.reject($q$delete from controller_security.revocations where credential_id=pg_temp.id(10)$q$);
select pg_temp.ok(not pg_has_role('authenticator','axiom_controller_issuer','MEMBER'),'PostgREST cannot assume issuer');
select pg_temp.ok(not pg_has_role('axiom_controller_issuer','service_role','MEMBER'),'issuer cannot inherit backend');
set local role axiom_assessment_controller;
select pg_temp.reject($q$select controller_security.issue_credential(current_setting('test.first'),pg_temp.hash(current_setting('test.first')))$q$);
select pg_temp.reject($q$select controller_security.revoke_credential(current_setting('test.revoke'),pg_temp.hash(current_setting('test.revoke')))$q$);
reset role;
set local role service_role;
select pg_temp.reject($q$select controller_security.issue_credential(current_setting('test.first'),pg_temp.hash(current_setting('test.first')))$q$);
reset role;
set local role authenticated;
select pg_temp.reject($q$select controller_security.issue_credential(current_setting('test.first'),pg_temp.hash(current_setting('test.first')))$q$);
reset role;
set local role anon;
select pg_temp.reject($q$select controller_security.issue_credential(current_setting('test.first'),pg_temp.hash(current_setting('test.first')))$q$);
reset role;
rollback;
