begin;
create function pg_temp.id(n int) returns uuid language sql immutable as $$select ('48480000-0000-4000-8000-'||lpad(n::text,12,'0'))::uuid$$;
create function pg_temp.ok(v boolean,m text) returns void language plpgsql as $$begin if v is distinct from true then raise exception 'ASSERTION: %',m; end if; end$$;
create function pg_temp.reject(q text,code text) returns void language plpgsql as $$begin begin execute q; exception when others then if sqlstate=code then return; end if; raise; end; raise exception 'Unexpected success'; end$$;
insert into auth.users(id,email) values(pg_temp.id(1),'worker-assessment@test.invalid');
insert into public.users(id,email) values(pg_temp.id(1),'worker-assessment@test.invalid');
insert into public.tenants(id,slug,name) values(pg_temp.id(11),'worker-assessment','Worker fixture');
insert into public.tenant_users(tenant_id,user_id,role) values(pg_temp.id(11),pg_temp.id(1),'owner');
insert into public.control_libraries(version,published_at,published_by,change_log,control_count)
 values('worker-assessment-v1',now(),'test','Synthetic fixture',2);
insert into public.controls(id,library_version,title,obligation,domain,severity,citations,evidence_required,assessment_questions,scoring,remediation_patterns,introduced_in_version)
 select 'WA-'||n,'worker-assessment-v1','Fixture','Fixture','SEC','low','[]','[]','[]','{"baseline":0,"weight":1,"penaltyPoints":10,"maxPenaltyINR":1000000}','{}','worker-assessment-v1' from generate_series(1,2) n;
insert into public.estates(id,tenant_id,name,slug) values(pg_temp.id(22),pg_temp.id(11),'Synthetic estate','synthetic');
insert into public.engagements(id,tenant_id,estate_id,library_version,title) values(pg_temp.id(21),pg_temp.id(11),pg_temp.id(22),'worker-assessment-v1','New assessment');
insert into public.workload_identities(id,tenant_id,agent_name,spiffe_id,status)
 values(pg_temp.id(31),pg_temp.id(11),'parikshan','spiffe://axiom.test/parikshan','active');
create temporary table issued as select (public.delegate_workload_task(pg_temp.id(11),pg_temp.id(1),pg_temp.id(31),'parikshan',pg_temp.id(22),pg_temp.id(21),pg_temp.id(41),repeat('a',64),repeat('b',64),array['control_library.read','findings.write'],clock_timestamp()+interval '10 minutes')->>'run_id')::uuid run_id;
grant select on issued to service_role;
create function pg_temp.start_tool(proof text default repeat('b',64),input_hash text default repeat('a',64),deadline timestamptz default clock_timestamp()+interval '5 minutes') returns jsonb language sql as $$
 select public.start_workload_assessment(pg_temp.id(11),(select run_id from issued),pg_temp.id(31),proof,input_hash,deadline)$$;
create function pg_temp.result() returns jsonb language sql immutable as $$select '{"library_version":"worker-assessment-v1","posture_score":50,"estimated_exposure_inr":10000000,"findings":[{"control_id":"WA-1","score":0,"risk_points":10,"rationale":"No answers comply"},{"control_id":"WA-2","score":100,"risk_points":0,"rationale":"All answers comply"}]}'::jsonb$$;
create function pg_temp.finish_tool(result jsonb default pg_temp.result(),deadline timestamptz default clock_timestamp()+interval '5 minutes') returns jsonb language sql as $$
 select public.complete_workload_assessment(pg_temp.id(11),(select run_id from issued),pg_temp.id(31),repeat('b',64),(select library_digest from public.workload_assessment_packets where run_id=(select run_id from issued)),result,deadline)$$;
set local role service_role;
select pg_temp.ok(pg_temp.start_tool(repeat('c',64))->>'error'='task_refused','wrong task proof cannot start');
select pg_temp.ok(pg_temp.start_tool(repeat('b',64),repeat('c',64))->>'error'='task_refused','wrong assigned input cannot start');
select pg_temp.ok(pg_temp.start_tool(repeat('b',64),repeat('a',64),clock_timestamp()-interval '1 second')->>'error'='task_refused','expired SVID cannot start');
select pg_temp.ok(pg_temp.start_tool()->>'library_version'='worker-assessment-v1','reads exact assigned library');
select pg_temp.ok(jsonb_array_length(pg_temp.start_tool()->'controls')=2,'start retry returns same complete packet');
select pg_temp.ok((select count(*)=1 from public.audit_ledger where tenant_id=pg_temp.id(11) and action_type='assessment.started'),'start audit exactly once');
select pg_temp.ok((select input_hash=repeat('a',64) from public.audit_ledger where tenant_id=pg_temp.id(11) and action_type='assessment.started'),'start audit binds assigned input');
select pg_temp.reject('delete from public.workload_assessment_packets','42501');
select pg_temp.reject('update public.workload_assessment_packets set result=null','42501');
select pg_temp.ok(pg_temp.finish_tool(jsonb_set(pg_temp.result(),'{library_version}','"other"'))->>'error'='invalid_result','wrong library refused');
select pg_temp.ok(pg_temp.finish_tool(jsonb_set(pg_temp.result(),'{findings,1,control_id}','"WA-1"'))->>'error'='invalid_result','duplicate controls refused');
select pg_temp.ok(pg_temp.finish_tool(jsonb_set(pg_temp.result(),'{findings,1,control_id}','"foreign"'))->>'error'='invalid_result','foreign control refused');
select pg_temp.ok(pg_temp.finish_tool(jsonb_set(pg_temp.result(),'{findings,0,score}','101'))->>'error'='invalid_result','score bounds enforced');
select pg_temp.ok(pg_temp.finish_tool(jsonb_set(pg_temp.result(),'{findings,1,rationale}','null'))->>'error'='invalid_result','whole batch validated before first write');
select pg_temp.ok((select count(*)=0 from public.findings where tenant_id=pg_temp.id(11)),'invalid batches have no partial rows');
select pg_temp.ok(pg_temp.finish_tool(pg_temp.result(),clock_timestamp()-interval '1 second')->>'error'='task_refused','expired SVID cannot write');
reset role;
savepoint halted;
update public.kill_switch_state set engaged=true where scope_key='global';
set local role service_role;
select pg_temp.ok(pg_temp.finish_tool()->>'error'='task_refused','halt checked inside write transaction');
reset role;
rollback to halted;
savepoint demoted;
update public.tenant_users set role='viewer' where user_id=pg_temp.id(1);
set local role service_role;
select pg_temp.ok(pg_temp.finish_tool()->>'error'='task_refused','demotion checked inside write transaction');
reset role;
rollback to demoted;
savepoint archived;
update public.estates set status='archived' where id=pg_temp.id(22);
set local role service_role;
select pg_temp.ok(pg_temp.finish_tool()->>'error'='task_refused','estate archival checked inside write transaction');
reset role;
rollback to archived;
-- Expiry after rows were tentatively written must abort the transaction.
create function pg_temp.delay_score_audit() returns trigger language plpgsql as $$begin if new.action_type='assessment.scored' then perform pg_sleep(2); end if; return new; end$$;
create trigger delay_score_audit before insert on public.audit_ledger for each row execute function pg_temp.delay_score_audit();
set local role service_role;
select pg_temp.reject('select pg_temp.finish_tool(pg_temp.result(),clock_timestamp()+interval ''1 second'')','42501');
select pg_temp.ok((select count(*)=0 from public.findings where tenant_id=pg_temp.id(11)),'expiry during audit rolls back findings');
select pg_temp.ok((select completed_receipt is null from public.workload_assessment_packets),'expiry during audit rolls back receipt');
reset role;
drop trigger delay_score_audit on public.audit_ledger;
-- A mandatory audit fault rolls back findings, scores, status and result receipt.
create function pg_temp.fail_score_audit() returns trigger language plpgsql as $$begin if new.action_type='assessment.scored' then raise exception 'synthetic audit failure'; end if; return new; end$$;
create trigger fail_score_audit before insert on public.audit_ledger for each row execute function pg_temp.fail_score_audit();
set local role service_role;
select pg_temp.reject('select pg_temp.finish_tool()','P0001');
select pg_temp.ok((select count(*)=0 from public.findings where tenant_id=pg_temp.id(11)),'audit fault rolls back findings');
select pg_temp.ok((select posture_score is null and status='assessment' from public.engagements where id=pg_temp.id(21)),'audit fault rolls back score and status');
select pg_temp.ok((select completed_receipt is null from public.workload_assessment_packets),'audit fault leaves no success receipt');
reset role;
drop trigger fail_score_audit on public.audit_ledger;
set local role service_role;
select pg_temp.ok(pg_temp.finish_tool()?'completed_receipt','persists complete result and receipt');
select pg_temp.ok(pg_temp.finish_tool()?'completed_receipt','identical retry is idempotent while task is live');
select pg_temp.ok(pg_temp.finish_tool(jsonb_set(pg_temp.result(),'{posture_score}','60'))->>'error'='result_conflict','changed retry cannot replace result');
select pg_temp.ok((select count(*)=2 from public.findings where engagement_id=pg_temp.id(21)),'all findings persist');
select pg_temp.ok((select score=0 from public.findings where control_id='WA-1' and engagement_id=pg_temp.id(21)),'zero score survives');
select pg_temp.ok((select posture_score=50 and estimated_exposure_inr=10000000 and status='review' from public.engagements where id=pg_temp.id(21)),'assessment moves to human review, not completion');
select pg_temp.ok((select count(*)=1 from public.audit_ledger where tenant_id=pg_temp.id(11) and action_type='assessment.scored'),'completion audit exactly once');
select pg_temp.ok((select input_hash=repeat('a',64) and output_hash is not null from public.audit_ledger where tenant_id=pg_temp.id(11) and action_type='assessment.scored'),'audit binds input and result');
reset role;
set local role authenticated;
select pg_temp.reject('select * from public.workload_assessment_packets','42501');
select pg_temp.reject('select pg_temp.start_tool()','42501');
select pg_temp.reject('select pg_temp.finish_tool()','42501');
reset role;
set local role anon;
select pg_temp.reject('select * from public.workload_assessment_packets','42501');
select pg_temp.reject('select pg_temp.start_tool()','42501');
reset role;
rollback;
