'use client';

import React, { useState } from 'react';
import { useRouter } from 'next/navigation';

/**
 * W8.3 — the founder review queue (BR-4).
 *
 * Nothing here decides anything: the rows are the database's recorded state,
 * and approve/reject/release go through the BFF routes whose RPCs enforce
 * the founder authority and the captured rejection reason. A refusal code is
 * shown verbatim. The published hash is sealed proof — it is the only gold
 * on this page, deliberately.
 */

export interface ReportRow {
  id: string;
  kind: string;
  title: string;
  status: string;
  generated_by_agent: string;
  generated_at: string;
  reviewed_by: string | null;
  rejection_reason: string | null;
  published_at: string | null;
  released_content_hash: string | null;
}

async function bridgePost(path: string, body: unknown): Promise<{ ok: boolean; code?: string }> {
  const res = await fetch(`/api/bff/v1${path}`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(body ?? {}),
  });
  const payload = (await res.json().catch(() => ({}))) as { error?: { code?: string } };
  if (!res.ok || payload.error) {
    return { ok: false, code: payload.error?.code ?? `http_${res.status}` };
  }
  return { ok: true };
}

export function ReviewQueue({ rows }: { rows: ReportRow[] }) {
  const router = useRouter();
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [rejecting, setRejecting] = useState<string | null>(null);

  async function act(path: string, body: unknown) {
    setBusy(true);
    setError(null);
    const result = await bridgePost(path, body);
    setBusy(false);
    if (!result.ok) {
      setError(result.code ?? 'refused');
      return;
    }
    setRejecting(null);
    router.refresh();
  }

  return (
    <section className="mx-auto max-w-4xl space-y-3 p-6 pt-0">
      <h2 className="text-xl font-semibold" style={{ color: '#1E2A4A' }}>
        Review queue
      </h2>
      <p className="text-sm text-slate-500">
        Unreviewed client output cannot be released. Approve or reject with a captured reason; only
        an approved report can be released.
      </p>

      {error ? (
        <div
          className="rounded-md border px-4 py-3 text-sm"
          style={{ borderColor: '#D9534F', color: '#D9534F' }}
          role="alert"
        >
          {error}
        </div>
      ) : null}

      {rows.length === 0 ? (
        <p className="rounded-lg border border-dashed border-slate-300 p-6 text-center text-sm text-slate-500">
          No reports recorded yet.
        </p>
      ) : null}

      {rows.map((row) => (
        <div key={row.id} className="rounded-lg border border-slate-200 bg-white p-4">
          <div className="flex flex-wrap items-center gap-2">
            <span className="font-medium" style={{ color: '#1E2A4A' }}>
              {row.title}
            </span>
            <span className="rounded-full bg-slate-100 px-2 py-0.5 text-xs text-slate-600">
              {row.kind}
            </span>
            <span className="rounded-full bg-slate-100 px-2 py-0.5 text-xs text-slate-600">
              {row.status}
            </span>
            {row.status === 'published' && row.released_content_hash ? (
              <span
                className="rounded-full px-2 py-0.5 font-mono text-xs"
                style={{ backgroundColor: '#C9A227', color: '#1E2A4A' }}
                title="Sealed proof: hash of the released content"
              >
                {row.released_content_hash.slice(0, 12)}…
              </span>
            ) : null}
          </div>
          <p className="mt-1 text-xs text-slate-500">
            Generated by {row.generated_by_agent} · {new Date(row.generated_at).toLocaleString()}
          </p>
          {row.status === 'rejected' && row.rejection_reason ? (
            <p className="mt-1 text-xs" style={{ color: '#D9534F' }}>
              Rejected: {row.rejection_reason}
            </p>
          ) : null}

          {row.status === 'draft' ? (
            <div className="mt-2 space-y-2">
              <div className="flex gap-2">
                <button
                  type="button"
                  disabled={busy}
                  onClick={() => act(`/reports/${row.id}/review`, { decision: 'approved' })}
                  className="rounded border px-2 py-1 text-xs font-medium disabled:opacity-50"
                  style={{ borderColor: '#0FB5A5', color: '#0FB5A5' }}
                >
                  Approve
                </button>
                <button
                  type="button"
                  disabled={busy}
                  onClick={() => setRejecting(rejecting === row.id ? null : row.id)}
                  className="rounded border px-2 py-1 text-xs font-medium disabled:opacity-50"
                  style={{ borderColor: '#D9534F', color: '#D9534F' }}
                >
                  Reject
                </button>
              </div>
              {rejecting === row.id ? (
                <form
                  className="flex gap-2"
                  action={(form: FormData) =>
                    act(`/reports/${row.id}/review`, {
                      decision: 'rejected',
                      note: String(form.get('note') ?? ''),
                    })
                  }
                >
                  <input
                    name="note"
                    required
                    maxLength={2000}
                    placeholder="Rejection reason (captured, required)"
                    className="flex-1 rounded-md border border-slate-300 px-2 py-1.5 text-sm"
                  />
                  <button
                    type="submit"
                    disabled={busy}
                    className="rounded px-3 py-1.5 text-xs font-medium text-white disabled:opacity-50"
                    style={{ backgroundColor: '#D9534F' }}
                  >
                    Record rejection
                  </button>
                </form>
              ) : null}
            </div>
          ) : null}

          {row.status === 'approved' ? (
            <button
              type="button"
              disabled={busy}
              onClick={() => act(`/reports/${row.id}/release`, {})}
              className="mt-2 rounded px-3 py-1.5 text-xs font-medium text-white disabled:opacity-50"
              style={{ backgroundColor: '#1E2A4A' }}
            >
              Release (founder)
            </button>
          ) : null}
        </div>
      ))}
    </section>
  );
}
