/** Server-only archive construction; exact stored manifest bytes are never normalized. */
import { createHash } from 'node:crypto';
import { readFileSync } from 'node:fs';
import { zipSync, type Zippable } from 'fflate';
import { ManifestV1Schema, ReviewV1Schema, PACK_LIMITS } from './schema';
const sha256 = (bytes: Uint8Array) => createHash('sha256').update(bytes).digest('hex');
/** JSON.parse validates grammar; a bounded lexical pass additionally rejects duplicate keys/depth. */
function strictJson(text: string): unknown {
  if (
    Buffer.byteLength(text, 'utf8') > PACK_LIMITS.metadataBytes ||
    Buffer.from(text, 'utf8').toString('utf8') !== text
  )
    throw new Error('Invalid manifest encoding or size');
  const stack: (Set<string> | null)[] = [];
  for (const match of text.matchAll(/"(?:\\[\s\S]|[^"\\])*"|[{}\[\]]/g)) {
    const token = match[0];
    if (token === '{' || token === '[') {
      stack.push(token === '{' ? new Set() : null);
      if (stack.length > 32) throw new Error('Manifest depth limit');
    } else if (token === '}' || token === ']') stack.pop();
    else if (stack.at(-1) && /^\s*:/.test(text.slice(match.index! + token.length))) {
      const key = JSON.parse(token) as string;
      const keys = stack.at(-1)!;
      if (keys.has(key)) throw new Error('Duplicate manifest key');
      keys.add(key);
    }
  }
  return JSON.parse(text) as unknown;
}
export function readManifestText(manifestText: string) {
  const manifest = ManifestV1Schema.parse(strictJson(manifestText));
  return { manifest, manifestText, manifestSha256: sha256(Buffer.from(manifestText, 'utf8')) };
}
export function readReviewText(reviewText: string) {
  const review = ReviewV1Schema.parse(strictJson(reviewText));
  return { review, reviewText, reviewSha256: sha256(Buffer.from(reviewText, 'utf8')) };
}
export function buildEvidencePack(input: {
  manifestText: string;
  expectedManifestSha256: string;
  reviewText: string;
  expectedReviewSha256: string;
  members: ReadonlyMap<string, Uint8Array>;
}) {
  const { manifest, manifestSha256 } = readManifestText(input.manifestText);
  if (manifestSha256 !== input.expectedManifestSha256)
    throw new Error('Stored manifest hash mismatch');
  const { review, reviewSha256 } = readReviewText(input.reviewText);
  if (reviewSha256 !== input.expectedReviewSha256) throw new Error('Stored review hash mismatch');
  if (
    review.pack_id !== manifest.pack_id ||
    review.manifest_sha256 !== manifestSha256 ||
    review.reviewed_at < manifest.created_at
  )
    throw new Error('Review does not bind this manifest');
  if (input.members.size !== manifest.members.length)
    throw new Error('Missing or undeclared member');
  const files: Zippable = Object.create(null) as Zippable;
  const add = (path: string, body: Uint8Array) => {
    if (!path.startsWith('evidence/') && body.byteLength > PACK_LIMITS.metadataBytes)
      throw new Error('Metadata byte limit');
    files[path] = [
      body,
      { level: 0, mtime: new Date(1980, 0, 1, 0, 0, 0), os: 3, attrs: 0o100644 << 16 },
    ];
  };
  add('manifest.json', Buffer.from(input.manifestText, 'utf8'));
  add('review.json', Buffer.from(input.reviewText, 'utf8'));
  const readme =
    [
      manifest.branding.product,
      manifest.branding.company,
      manifest.branding.company_url,
      '',
      `Pack: ${manifest.pack_id}`,
      `Title: ${manifest.title}`,
      `Generated by: ${manifest.generator.name} ${manifest.generator.version}`,
      `Approved by: ${review.reviewer.display_name} (${review.reviewer.id}) at ${review.reviewed_at}`,
      `Reviewed manifest SHA-256: ${manifestSha256}`,
      '',
      'Verify with a separately trusted copy of verify_evidence_pack.py and a separately obtained released archive SHA-256.',
      'Do not execute the bundled script before independently checking the outer archive digest.',
      'Checksums are not signatures. Storage verification does not establish provenance or regulatory completeness.',
      'Reference and sandbox sources are excluded. Human-submitted and unknown provenance remain unverified assertions.',
      '',
      ...manifest.limitations,
    ].join('\n') + '\n';
  add('README.txt', Buffer.from(readme, 'utf8'));
  const verifier = readFileSync(new URL('../python/verify_evidence_pack.py', import.meta.url));
  if (verifier.length > PACK_LIMITS.metadataBytes) throw new Error('Verifier byte limit');
  add('verify_evidence_pack.py', verifier);
  let total = 0;
  for (const member of manifest.members) {
    const bytes = input.members.get(member.evidence_id);
    if (
      !bytes ||
      bytes.byteLength !== member.byte_size ||
      bytes.byteLength > PACK_LIMITS.memberBytes ||
      sha256(bytes) !== member.content_hash
    )
      throw new Error('Member bytes do not match manifest');
    total += bytes.byteLength;
    if (total > PACK_LIMITS.aggregateBytes) throw new Error('Aggregate evidence byte limit');
    add(member.path, bytes);
  }
  const archive = Buffer.from(zipSync(files, { level: 0 }));
  if (archive.length > PACK_LIMITS.archiveBytes) throw new Error('Archive byte limit');
  return { archive, archiveSha256: sha256(archive), byteSize: archive.length };
}
