/**
 * Stateless PDF renderer for report-kit.
 * Uses local headless Chromium / chrome-headless-shell when available,
 * with deterministic standard conforming %PDF-1.4 fallback engine.
 */
import { execFile } from 'node:child_process';
import { createHash, randomUUID } from 'node:crypto';
import { existsSync, promises as fs } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { promisify } from 'node:util';

const execFileAsync = promisify(execFile);

export interface RenderPdfOptions {
  timeoutMs?: number;
  preferChromium?: boolean;
}

export interface RenderPdfResult {
  pdfBuffer: Buffer;
  sha256: string;
  byteLength: number;
  renderer: 'chromium' | 'deterministic-fallback';
}

/** Known locations for headless chromium / chrome-headless-shell */
function findChromiumExecutable(): string | null {
  if (process.env.CHROME_PATH && existsSync(process.env.CHROME_PATH)) {
    return process.env.CHROME_PATH;
  }
  if (
    process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE_PATH &&
    existsSync(process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE_PATH)
  ) {
    return process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE_PATH;
  }

  const home = process.env.HOME || '';
  const candidates = [
    // Playwright standard cache paths
    join(
      home,
      'Library/Caches/ms-playwright/chromium_headless_shell-1243/chrome-headless-shell-mac-arm64/chrome-headless-shell',
    ),
    join(
      home,
      'Library/Caches/ms-playwright/chromium_headless_shell-1234/chrome-headless-shell-mac-arm64/chrome-headless-shell',
    ),
    join(
      home,
      '.cache/ms-playwright/chromium_headless_shell-1243/chrome-headless-shell-linux/chrome-headless-shell',
    ),
    join(home, '.cache/ms-playwright/chromium-1243/chrome-linux/chrome'),
    // System installations
    '/usr/bin/chromium',
    '/usr/bin/chromium-browser',
    '/usr/bin/google-chrome',
    '/usr/bin/google-chrome-stable',
    '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',
  ];

  for (const c of candidates) {
    if (c && existsSync(c)) {
      return c;
    }
  }
  return null;
}

/**
 * Safely extracts visible text from HTML using a linear character scanner without
 * regular expressions, preventing polynomial backtracking (ReDoS) and sanitization bypasses.
 */
function extractVisibleText(htmlContent: string): string {
  let inTag = false;
  let inScript = false;
  let inStyle = false;
  let currentTag = '';
  let result = '';

  for (let i = 0; i < htmlContent.length; i++) {
    const char = htmlContent[i];
    if (char === '<') {
      inTag = true;
      currentTag = '';
    } else if (char === '>') {
      inTag = false;
      const tagLower = currentTag.trim().toLowerCase();
      if (tagLower.startsWith('script')) {
        inScript = true;
      } else if (tagLower.startsWith('/script')) {
        inScript = false;
      } else if (tagLower.startsWith('style')) {
        inStyle = true;
      } else if (tagLower.startsWith('/style')) {
        inStyle = false;
      }
      result += ' ';
    } else if (inTag) {
      currentTag += char;
    } else if (!inScript && !inStyle) {
      result += char;
    }
  }

  // Collapse whitespaces linearly without regex
  let collapsed = '';
  let prevSpace = false;
  for (let i = 0; i < result.length; i++) {
    const c = result[i];
    if (c === ' ' || c === '\t' || c === '\n' || c === '\r') {
      if (!prevSpace) {
        collapsed += ' ';
        prevSpace = true;
      }
    } else {
      collapsed += c;
      prevSpace = false;
    }
  }
  return collapsed.trim();
}

/**
 * Safely extracts document title without regular expressions.
 */
function extractTitle(htmlContent: string): string {
  const startIdx = htmlContent.toLowerCase().indexOf('<title>');
  if (startIdx === -1) return 'Axiom Proof Board Report';
  const afterStart = startIdx + 7;
  const endIdx = htmlContent.toLowerCase().indexOf('</title>', afterStart);
  if (endIdx === -1) return 'Axiom Proof Board Report';
  const title = htmlContent.slice(afterStart, endIdx).trim();
  return title || 'Axiom Proof Board Report';
}

/**
 * Deterministically generates a compliant, minimal %PDF-1.4 document buffer from HTML text.
 * Used when headless browser is absent or disabled.
 */
function generateDeterministicPdf(htmlContent: string): Buffer {
  const title = extractTitle(htmlContent);

  // Extract a few visible text lines for PDF stream safely without regex backtracking
  const cleanText = extractVisibleText(htmlContent);

  const snippet = cleanText.slice(0, 1500).replace(/[()\\]/g, '\\$&');

  const streamContent = `BT
/F1 18 Tf
50 780 Td
(${title.replace(/[()\\]/g, '\\$&')}) Tj
/F1 10 Tf
0 -30 Td
(Generated by Axiom Proof Deterministic Engine) Tj
0 -20 Td
(${snippet.slice(0, 100)}) Tj
0 -15 Td
(${snippet.slice(100, 200)}) Tj
0 -15 Td
(${snippet.slice(200, 300)}) Tj
0 -15 Td
(${snippet.slice(300, 400)}) Tj
0 -15 Td
(${snippet.slice(400, 500)}) Tj
ET`;

  const streamLength = Buffer.byteLength(streamContent, 'utf-8');

  const objects = [
    // 1: Catalog
    '1 0 obj\n<< /Type /Catalog /Pages 2 0 R >>\nendobj',
    // 2: Pages
    '2 0 obj\n<< /Type /Pages /Kids [3 0 R] /Count 1 >>\nendobj',
    // 3: Page
    '3 0 obj\n<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595.28 841.89] /Contents 4 0 R /Resources << /Font << /F1 5 0 R >> >> >>\nendobj',
    // 4: Contents
    `4 0 obj\n<< /Length ${streamLength} >>\nstream\n${streamContent}\nendstream\nendobj`,
    // 5: Font
    '5 0 obj\n<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>\nendobj',
  ];

  let pdfStr = '%PDF-1.4\n';
  const offsets: number[] = [0];

  for (const obj of objects) {
    offsets.push(Buffer.byteLength(pdfStr, 'utf-8'));
    pdfStr += obj + '\n';
  }

  const xrefOffset = Buffer.byteLength(pdfStr, 'utf-8');
  pdfStr += 'xref\n0 6\n0000000000 65535 f \n';

  for (let i = 1; i <= 5; i++) {
    pdfStr += `${offsets[i]!.toString().padStart(10, '0')} 00000 n \n`;
  }

  pdfStr += `trailer\n<< /Size 6 /Root 1 0 R >>\nstartxref\n${xrefOffset}\n%%EOF\n`;
  return Buffer.from(pdfStr, 'utf-8');
}

/**
 * Render HTML to deterministic PDF buffer.
 */
export async function renderHtmlToPdf(
  htmlContent: string,
  options: RenderPdfOptions = {},
): Promise<RenderPdfResult> {
  const timeoutMs = options.timeoutMs ?? 15000;
  const preferChromium = options.preferChromium ?? true;

  const chromiumPath = preferChromium ? findChromiumExecutable() : null;

  if (chromiumPath) {
    const tempPrefix = join(tmpdir(), `axiom-report-${Date.now()}-${randomUUID()}`);
    const inHtmlPath = `${tempPrefix}.html`;
    const outPdfPath = `${tempPrefix}.pdf`;

    try {
      await fs.writeFile(inHtmlPath, htmlContent, 'utf-8');

      await execFileAsync(
        chromiumPath,
        [
          '--headless',
          '--disable-gpu',
          '--no-sandbox',
          '--disable-setuid-sandbox',
          '--no-pdf-header-footer',
          `--print-to-pdf=${outPdfPath}`,
          inHtmlPath,
        ],
        { timeout: timeoutMs },
      );

      const pdfBuffer = await fs.readFile(outPdfPath);
      const sha256 = createHash('sha256').update(pdfBuffer).digest('hex');

      return {
        pdfBuffer,
        sha256,
        byteLength: pdfBuffer.length,
        renderer: 'chromium',
      };
    } catch {
      // Fallback cleanly to deterministic generator if headless process fails or is blocked
    } finally {
      await fs.unlink(inHtmlPath).catch(() => {});
      await fs.unlink(outPdfPath).catch(() => {});
    }
  }

  const pdfBuffer = generateDeterministicPdf(htmlContent);
  const sha256 = createHash('sha256').update(pdfBuffer).digest('hex');

  return {
    pdfBuffer,
    sha256,
    byteLength: pdfBuffer.length,
    renderer: 'deterministic-fallback',
  };
}
